version: '3.1'
services:
  # Racio
  COW-Racio-01:
    # image: zhayujie/chatgpt-on-wechat
    image: qyl/chatgpt-on-wechat:1.5.4 
    restart: always
    container_name: Racio
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: 'YOUR API KEY'
      MODEL: 'gpt-3.5-turbo-16k'
      CHANNEL_TYPE: 'wx'
      PROXY: ''
      HOT_RELOAD: True
      CLEAR_MEMORY_COMMANDS: '["#清除记忆", "#清除所有", "#更新配置"]'

      SINGLE_CHAT_PREFIX: '["Racio", "@Racio"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[Racio] "'
      GROUP_CHAT_PREFIX: '["@Racio"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      GROUP_CHAT_IN_ONE_SESSION: '["智人家族"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'

      CONVERSATION_MAX_TOKENS: 8000
      EXPIRES_IN_SECONDS: 3600
      REQUEST_TIMEOUT: 600
      TIMEOUT: 480
      USE_GLOBAL_PLUGIN_CONFIG: 'True'

      SPEECH_RECOGNITION: 'False'
      GROUP_SPEECH_RECOGNITION: 'False'
      VOICE_REPLY_VOICE: 'False'
      CHARACTER_DESC: '你是睿轩智人, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      TEMPERATURE: 0.7
      TOP_P: 1
      SUBSCRIBE_MSG: "感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。"

      USE_LINKAI: 'False'
      LINKAI_API_KEY: 'Link_Fmn'
      LINKAI_APP_CODE: 'Jy'

      USE_RACIO: 'True'
      RACIO_API_BASE: 'https://kb.racio.ai'
      RACIO_API_KEY: 'app-key'
      RACIO_APP_CODE: 'RACIO_APP_CODE-Racio'
      RACIO_USER_ID: 'COW-Racio01-Racio-'
    volumes:
      # Mount the storage directory to the container, for plugins config.json in container
      - ./plugins/config-racio.json:/app/plugins/config.json
      # Mount the storage directory to the container, for storing user files.
      # - ./volumes/app/storage/data.racio/itchat.pkl:/app/itchat.pkl
      - ./volumes/app/storage/data.racio/user_datas.pkl:/app/user_datas.pkl
      - ./volumes/app/storage/data.racio/run.log:/app/run.log
      - ./volumes/app/storage/data.racio/tool.log:/app/tool.log
      - ./volumes/app/storage/data.racio/plugins.json:/app/plugins/plugins.json
  
  # Py_rally
  COW-Racio-02:
    # image: zhayujie/chatgpt-on-wechat
    image: qyl/chatgpt-on-wechat:1.5.4 
    restart: always
    container_name: Py_rally
    security_opt:
      - seccomp:unconfined
    environment:
      MODEL: 'gpt-3.5-turbo-16k'
      CHANNEL_TYPE: 'wx'
      PROXY: ''
      HOT_RELOAD: True
      CLEAR_MEMORY_COMMANDS: '["#清除记忆", "#清除所有", "#更新配置"]'

      SINGLE_CHAT_PREFIX: '["鲨哥(Py Rally)", "@鲨哥(Py Rally)"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[鲨哥(Py Rally)] "'
      GROUP_CHAT_PREFIX: '["@鲨哥(Py Rally)"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      GROUP_CHAT_IN_ONE_SESSION: '["智人家族"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'

      CONVERSATION_MAX_TOKENS: 12000
      EXPIRES_IN_SECONDS: 3600
      REQUEST_TIMEOUT: 600
      TIMEOUT: 480
      USE_GLOBAL_PLUGIN_CONFIG: 'True'

      SPEECH_RECOGNITION: 'False'
      GROUP_SPEECH_RECOGNITION: 'False'
      VOICE_REPLY_VOICE: 'False'
      CHARACTER_DESC: '你是睿轩智人, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      TEMPERATURE: 0.7
      TOP_P: 1
      SUBSCRIBE_MSG: "感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。"

      USE_LINKAI: 'False'
      LINKAI_API_KEY: 'Link_Fmn'
      LINKAI_APP_CODE: 'Jy'

      USE_RACIO: 'True'
      RACIO_API_BASE: 'https://kb.racio.ai'
      RACIO_API_KEY: 'app-key'
      RACIO_APP_CODE: 'RACIO_APP_CODE-Py_rally-闪电侠⚡️'
      RACIO_USER_ID: 'COW-Racio02-鲨哥(Py Rally)-'
    volumes:
      # Mount the storage directory to the container, for plugins config.json in container
      - ./plugins/config-py_rally.json:/app/plugins/config.json
      # Mount the storage directory to the container, for storing user files.
      # - ./volumes/app/storage/data.py_rally/itchat.pkl:/app/itchat.pkl
      - ./volumes/app/storage/data.py_rally/user_datas.pkl:/app/user_datas.pkl
      - ./volumes/app/storage/data.py_rally/run.log:/app/run.log
      - ./volumes/app/storage/data.py_rally/tool.log:/app/tool.log
      - ./volumes/app/storage/data.py_rally/plugins.json:/app/plugins/plugins.json

  # Trader
  COW-Racio-03:
    # image: zhayujie/chatgpt-on-wechat
    image: qyl/chatgpt-on-wechat:1.5.4 
    restart: always
    container_name: Trader
    security_opt:
      - seccomp:unconfined
    environment:
      MODEL: 'gpt-3.5-turbo-16k'
      CHANNEL_TYPE: 'wx'
      PROXY: ''
      HOT_RELOAD: True
      CLEAR_MEMORY_COMMANDS: '["#清除记忆", "#清除所有", "#更新配置"]'

      SINGLE_CHAT_PREFIX: '["Trader", "@Trader"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[Trader] "'
      GROUP_CHAT_PREFIX: '["@Trader"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      GROUP_CHAT_IN_ONE_SESSION: '["智人家族"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'

      CONVERSATION_MAX_TOKENS: 12000
      EXPIRES_IN_SECONDS: 3600
      REQUEST_TIMEOUT: 600
      TIMEOUT: 480
      USE_GLOBAL_PLUGIN_CONFIG: 'True'

      SPEECH_RECOGNITION: 'False'
      GROUP_SPEECH_RECOGNITION: 'False'
      VOICE_REPLY_VOICE: 'False'
      CHARACTER_DESC: '你是睿轩智人, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      TEMPERATURE: 0.7
      TOP_P: 1
      SUBSCRIBE_MSG: "感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。"

      USE_LINKAI: 'False'
      LINKAI_API_KEY: 'Link_Fmn'
      LINKAI_APP_CODE: 'Jy'

      USE_RACIO: 'True'
      RACIO_API_BASE: 'https://kb.racio.ai'
      RACIO_API_KEY: 'app-key'
      RACIO_APP_CODE: 'RACIO_APP_CODE-Trader_掌门'
      RACIO_USER_ID: 'COW-Racio03-Trader-'
    volumes:
      # Mount the storage directory to the container, for plugins config.json in container
      - ./plugins/config-trader.json:/app/plugins/config.json
      # Mount the storage directory to the container, for storing user files.
      # - ./volumes/app/storage/data.trader/itchat.pkl:/app/itchat.pkl
      - ./volumes/app/storage/data.trader/user_datas.pkl:/app/user_datas.pkl
      - ./volumes/app/storage/data.trader/run.log:/app/run.log
      - ./volumes/app/storage/data.trader/tool.log:/app/tool.log
      - ./volumes/app/storage/data.trader/plugins.json:/app/plugins/plugins.json

  # Wonder
  COW-Dify-01:
    # image: zhayujie/chatgpt-on-wechat
    image: qyl/chatgpt-on-wechat:1.5.4 
    restart: always
    container_name: Wonder
    security_opt:
      - seccomp:unconfined
    environment:
      MODEL: 'gpt-3.5-turbo-16k'
      CHANNEL_TYPE: 'wx'
      PROXY: ''
      HOT_RELOAD: True
      CLEAR_MEMORY_COMMANDS: '["#清除记忆", "#清除所有", "#更新配置"]'

      SINGLE_CHAT_PREFIX: '["Wonder", "@Wonder"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[Wonder] "'
      GROUP_CHAT_PREFIX: '["@Wonder"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      GROUP_CHAT_IN_ONE_SESSION: '["智人家族"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'

      CONVERSATION_MAX_TOKENS: 12000
      EXPIRES_IN_SECONDS: 3600
      REQUEST_TIMEOUT: 600
      TIMEOUT: 480
      USE_GLOBAL_PLUGIN_CONFIG: 'True'

      SPEECH_RECOGNITION: 'False'
      GROUP_SPEECH_RECOGNITION: 'False'
      VOICE_REPLY_VOICE: 'False'
      CHARACTER_DESC: '你是睿轩智人, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      TEMPERATURE: 0.7
      TOP_P: 1
      SUBSCRIBE_MSG: "感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。"

      USE_LINKAI: 'False'
      LINKAI_API_KEY: 'Link_Fmn'
      LINKAI_APP_CODE: 'Jy'

      USE_RACIO: 'True'
      RACIO_API_BASE: 'https://api.dify.ai'
      RACIO_API_KEY: 'app-key'
      RACIO_APP_CODE: 'RACIO_APP_CODE-Dify_on_WeChat-钢铁侠'
      RACIO_USER_ID: 'COW-Dify01-Wonder-'
    volumes:
      # Mount the storage directory to the container, for plugins config.json in container
      - ./plugins/config-wonder.json:/app/plugins/config.json
      # Mount the storage directory to the container, for storing user files.
      # - ./volumes/app/storage/data.wonder/itchat.pkl:/app/itchat.pkl
      - ./volumes/app/storage/data.wonder/user_datas.pkl:/app/user_datas.pkl
      - ./volumes/app/storage/data.wonder/run.log:/app/run.log
      - ./volumes/app/storage/data.wonder/tool.log:/app/tool.log
      - ./volumes/app/storage/data.wonder/plugins.json:/app/plugins/plugins.json

  # Master
  COW-LinkAI-01:
    # image: zhayujie/chatgpt-on-wechat
    image: qyl/chatgpt-on-wechat:1.5.4 
    restart: always
    container_name: Master
    security_opt:
      - seccomp:unconfined
    environment:
      MODEL: 'gpt-3.5-turbo-16k'
      CHANNEL_TYPE: 'wx'
      PROXY: ''
      HOT_RELOAD: True
      CLEAR_MEMORY_COMMANDS: '["#清除记忆", "#清除所有", "#更新配置"]'

      SINGLE_CHAT_PREFIX: '["Master", "@Master"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[Master] "'
      GROUP_CHAT_PREFIX: '["@Master"]'
      GROUP_NAME_WHITE_LIST: '["ALL_GROUP"]'
      GROUP_CHAT_IN_ONE_SESSION: '["智人家族"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'

      CONVERSATION_MAX_TOKENS: 12000
      EXPIRES_IN_SECONDS: 3600
      REQUEST_TIMEOUT: 600
      TIMEOUT: 480
      USE_GLOBAL_PLUGIN_CONFIG: 'True'

      SPEECH_RECOGNITION: 'False'
      GROUP_SPEECH_RECOGNITION: 'False'
      VOICE_REPLY_VOICE: 'False'
      CHARACTER_DESC: '你是睿轩智人, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      TEMPERATURE: 0.7
      TOP_P: 1
      SUBSCRIBE_MSG: "感谢您的关注！\n这里是ChatGPT，可以自由对话。\n支持语音对话。\n支持图片输入。\n支持图片输出，画字开头的消息将按要求创作图片。\n支持tool、角色扮演和文字冒险等丰富的插件。\n输入{trigger_prefix}#help 查看详细指令。"

      USE_LINKAI: 'True'
      LINKAI_API_KEY: 'Link_'
      LINKAI_APP_CODE: 'app-code'

      USE_RACIO: 'False'
      RACIO_API_BASE: 'https://kb.racio.ai'
      RACIO_API_KEY: 'app-key'
      RACIO_APP_CODE: 'RACIO_APP_CODE-Master'
      RACIO_USER_ID: 'COW-LinkAI01-Master-'
    volumes:
      # Mount the storage directory to the container, for plugins config.json in container
      - ./plugins/config-master.json:/app/plugins/config.json
      # Mount the storage directory to the container, for storing user files.
      # - ./volumes/app/storage/data.master/itchat.pkl:/app/itchat.pkl
      - ./volumes/app/storage/data.master/user_datas.pkl:/app/user_datas.pkl
      - ./volumes/app/storage/data.master/run.log:/app/run.log
      - ./volumes/app/storage/data.master/tool.log:/app/tool.log
      - ./volumes/app/storage/data.master/plugins.json:/app/plugins/plugins.json
