version: '2.0'
services:
  chatgpt-on-wechat:
    image: zhayujie/chatgpt-on-wechat
    container_name: chatgpt-on-wechat
    security_opt:
      - seccomp:unconfined
    environment:
      OPEN_AI_API_KEY: 'YOUR API KEY'
      MODEL: 'gpt-3.5-turbo-16k'
      PROXY: ''
      SINGLE_CHAT_PREFIX: '["Racio", "@Racio"]'
      SINGLE_CHAT_REPLY_PREFIX: '"[Racio] "'
      GROUP_CHAT_PREFIX: '["@Racio"]'
      GROUP_NAME_WHITE_LIST: '["智人团-01群", "智人团-01群"]'
      IMAGE_CREATE_PREFIX: '["画", "看", "找"]'
      CONVERSATION_MAX_TOKENS: 1000
      SPEECH_RECOGNITION: 'False'
      CHARACTER_DESC: '你是睿轩智人, 一个由OpenAI训练的大型语言模型, 你旨在回答并解决人们的任何问题，并且可以使用多种语言与人交流。'
      EXPIRES_IN_SECONDS: 3600
      USE_GLOBAL_PLUGIN_CONFIG: 'True'
      USE_LINKAI: 'False'
      LINKAI_API_KEY: 'Link_FmnEMTGiTwF1i5mfjqjqcZjPS046sPDTbSHNIAIBkF'
      LINKAI_APP_CODE: 'JyqspjQz'
      USE_RACIO: 'True'
      RACIO_API_BASE: 'https://kb.racio.ai'
      RACIO_API_KEY: 'app-dZnMOhQqtGgkwx5eCh3dBYYf'
      RACIO_APP_CODE: 'RACIO_APP_CODE'
      RACIO_USER_ID: 'racio_wechat_bot_from_aws_instances'
